version: "3"

services:
  SiteNoteMongoDB:
    image: mongo:latest
    command: mongod --port 27018
    restart: always
    ports:
      - "27018:27018"
    volumes:
      - SiteNoteMongoDB:/data/db
    networks:
      - sitenote-network
  SiteNoteServer:
    image: segelfartyg/sitenote-server:latest
    restart: always
    ports:
     - "9000:9000"
    depends_on:
      SiteNoteMongoDB:
        condition: service_started
    networks:
      - sitenote-network
  SiteNoteFrontend:
    image: segelfartyg/sitenote-frontend:latest
    restart: always
    ports:
     - "5173:5173"
    depends_on:
      SiteNoteMongoDB:
        condition: service_started
    networks:
      - sitenote-network
  
networks:
  sitenote-network:
    driver: bridge
volumes:
  SiteNoteMongoDB: {}