version: "3"

services:
  SiteNoteMongoDB:
    image: mongo:latest
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - SiteNoteMongoDB:/data/db
    networks:
      - sitenote-network
  SiteNoteServer:
    image: segelfartyg/sitenote.server
    restart: always
    ports:
     - "9000:9000"
    depends_on:
      SiteNoteMongoDB:
        condition: service_started
    networks:
      - sitenote-network
networks:
  sitenote-network:
    driver: bridge
volumes:
  SiteNoteMongoDB: {}