name: sitenote-frontend-ci

on:
  push:
    branches:
      - main
    paths:
      - SiteNote.Web.Proxy/**

jobs:
  Build:
    runs-on: ubuntu-latest
    steps:
      -
        name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
      -
        name: Install GitVersion
        uses: gittools/actions/gitversion/setup@v1.2.0
        with:
          versionSpec: '5.x'
      -
        name: Determine Version
        id: version_step # step id used as reference for output values
        uses: gittools/actions/gitversion/execute@v1.2.0

      - 
        run: |
          echo "FullSemVer (env.fullSemVer)            : ${{ env.fullSemVer }}"
          version=${{ env.fullSemVer }}
          version_refined="${version//+/-beta-}"
          echo $version
          echo "FINALVERSION=$(echo $version_refined)" >> $GITHUB_ENV
        name: Display GitVersion variables (without prefix)

      -
        name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      -
        name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
      -
        name: Build and push
        uses: docker/build-push-action@v5
        with:
          context: ./SiteNote.Web.Proxy
          file: ./SiteNote.Web.Proxy/Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/sitenote:frontend-${{ env.FINALVERSION }}
      # -
      #   name: DO Deployment
      #   uses: appleboy/ssh-action@v0.1.2
      #   with:
      #     host: ${{secrets.SSH_HOST}}
      #     key: ${{secrets.SSH_KEY}}
      #     username: ${{secrets.SSH_USERNAME}}

      #     script: | 
      #       cd ${{ secrets.SPLODO_DIRECTORY }}
      #       docker-compose down
      #       docker rmi ${{ secrets.DOCKERHUB_USERNAME }}/splodo:splodo.web -f
      #       docker-compose up -d